package com.gaproject.mmaer;

public class MessageParser {
	
	private  boolean isAppMessage;
	private  boolean isAcknowledgement;
	private  String  messageStamp;
	private  String  messageContent;
	private  String  msg;
	
	public static final String APPLICATION_STAMP= "*!="; // a delimiter to be used to filter  SMS/Messages that 
														 // are generated by the MMAER APP (the first 3 char of any msg)
	public static final String ACK_STAMP="ACK";// a delimiter to be used to filter acknowledgments msgs from other msgs
											   // msg.substring(3,6)

	public MessageParser(String msg)
	{
		this.msg =msg;
		processMSG(msg);
	}
	
	
	public void processMSG(String msg)
	{
		if(this.msg!=null && this.msg.length()>=9)
		{
			if(this.msg.substring(0,3).equals(APPLICATION_STAMP))
				isAppMessage=true;
			else
				isAppMessage=false;
		
			if(this.msg.substring(3,6).equals(ACK_STAMP))
				isAcknowledgement=true;
			else
				isAcknowledgement=false;
		
			this.messageStamp= this.msg.substring(6,9);
			this.messageContent= this.msg.substring(9);
		}
		else
		{
			this.isAppMessage=false;
			this.isAcknowledgement=false;
		}
	}
	
	public boolean isAppMessage()
	{
		return isAppMessage;
	}
	
	public boolean isAcknowledgement()
	{
		return isAcknowledgement;
	}
	
	public String getMessage()
	{
		return messageContent;
	}
	
	public String getMessageStamp()
	{
		return messageStamp;
	}
	
}
